stages:
  - build
  #- sonarqube

before_script:
  - git reset --hard $CI_COMMIT_SHA
  - git clean -df
  - git stash
  - git pull origin $CI_COMMIT_SHA
  
svarog-jts-io:
  stage: build
  script:  
    - pwd
    - mvn clean compile
    - mvn install